import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import LeftSideBar from "../../components/layout/LeftSideBar";
import TopBar from "../../components/layout/TopBar";
import { ToasterProvider } from "../../lib/ToastProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <ToasterProvider></ToasterProvider>
          <div className="flex max-lg:flex-col">
            <LeftSideBar></LeftSideBar>
            <TopBar></TopBar>
            <div className="flex-1 p-10">
              {children}
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
